### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by joelwking** [nsthompson/ansible-collection-dependencies#3]
I tested the code in Python2 using a Vagrantfile to build a VM.

Set my path: `export PYTHONPATH=~/ansible/playbooks/ansible-collection-dependencies`

Create ` touch lib/__init__.py`.

And used the 'format' method instead of the `f'` formatting of Python3, e.g. `('{}'.format(playbook_path)`

with those changes, the code is running in Python2.

**Comment by nsthompson** [comment]
Added lib/__init__.py, but left f-strings.  Python2 has lived a good life. ;)
